# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KdxDev < Formula
  desc "Kodexa CLI (Dev) - Development build of the Kodexa platform CLI"
  homepage "https://www.kodexa.com"
  version "2026.13.0-develop-37612953022"
  license "Proprietary"

  on_macos do
    on_intel do
      url "https://github.com/kodexa-ai/kdx-cli-releases/releases/download/v2026.13.0-develop-37612953022/kdx-dev_2026.13.0-develop-37612953022_darwin_x86_64.tar.gz"
      sha256 "86edf82c8e2d1764c972515137988e4b9a2435bffbea67f1d441164c483ed866"

      def install
        bin.install "kdx-dev"
      end
    end
    on_arm do
      url "https://github.com/kodexa-ai/kdx-cli-releases/releases/download/v2026.13.0-develop-37612953022/kdx-dev_2026.13.0-develop-37612953022_darwin_arm64.tar.gz"
      sha256 "5203be3c18c6669f0498204c241571495549721a103d82632f9e60c366a18f56"

      def install
        bin.install "kdx-dev"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kodexa-ai/kdx-cli-releases/releases/download/v2026.13.0-develop-37612953022/kdx-dev_2026.13.0-develop-37612953022_linux_x86_64.tar.gz"
        sha256 "9a25aadf24975caf07aeb6029405bd775a7f00712f3db02c72d8fdd985865049"

        def install
          bin.install "kdx-dev"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kodexa-ai/kdx-cli-releases/releases/download/v2026.13.0-develop-37612953022/kdx-dev_2026.13.0-develop-37612953022_linux_arm64.tar.gz"
        sha256 "240f921943fd4f56c6199cba556728233167e49b59ddb603b2d65d2ced009561"

        def install
          bin.install "kdx-dev"
        end
      end
    end
  end

  def caveats
    <<~EOS
      This is a development pre-release of the Kodexa CLI.
      The binary is installed as 'kdx-dev' so it can coexist with the stable 'kdx'.

      To get started:
        kdx-dev --help

      For the stable version:
        brew install kodexa-ai/tap/kdx

      For support: support@kodexa.com
    EOS
  end

  test do
    system "#{bin}/kdx-dev", "--version"
  end
end
