# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KdxDev < Formula
  desc "Kodexa CLI (Dev) - Development build of the Kodexa platform CLI"
  homepage "https://www.kodexa.com"
  version "2026.3.0-develop-24606701964"
  license "Proprietary"

  on_macos do
    on_intel do
      url "https://github.com/kodexa-ai/kdx-cli-releases/releases/download/v2026.3.0-develop-24606701964/kdx-dev_2026.3.0-develop-24606701964_darwin_x86_64.tar.gz"
      sha256 "cbf8fc6aed289a089fd6bd65630c10d75b18ca1414e2d075f8146ecf77db1b23"

      def install
        bin.install "kdx-dev"
      end
    end
    on_arm do
      url "https://github.com/kodexa-ai/kdx-cli-releases/releases/download/v2026.3.0-develop-24606701964/kdx-dev_2026.3.0-develop-24606701964_darwin_arm64.tar.gz"
      sha256 "0378496961f9c7d74755b62443430d66333dea7cd2dd27c7c243c767b8ada3e5"

      def install
        bin.install "kdx-dev"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kodexa-ai/kdx-cli-releases/releases/download/v2026.3.0-develop-24606701964/kdx-dev_2026.3.0-develop-24606701964_linux_x86_64.tar.gz"
        sha256 "421f76102891d97c2472b9c181688cc2b5d5754fa9b6d9b0daf527efcef5ae67"

        def install
          bin.install "kdx-dev"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kodexa-ai/kdx-cli-releases/releases/download/v2026.3.0-develop-24606701964/kdx-dev_2026.3.0-develop-24606701964_linux_arm64.tar.gz"
        sha256 "2aaf3e6a6ee1600ccfb736c371c79e484fa594a2ab6f7aa67260932ff8a55d49"

        def install
          bin.install "kdx-dev"
        end
      end
    end
  end

  def caveats
    <<~EOS
      This is a development pre-release of the Kodexa CLI.
      The binary is installed as 'kdx-dev' so it can coexist with the stable 'kdx'.

      To get started:
        kdx-dev --help

      For the stable version:
        brew install kodexa-ai/tap/kdx

      For support: support@kodexa.com
    EOS
  end

  test do
    system "#{bin}/kdx-dev", "--version"
  end
end
