# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KdxDev < Formula
  desc "Kodexa CLI (Dev) - Development build of the Kodexa platform CLI"
  homepage "https://www.kodexa.com"
  version "2026.11.0-develop-32016774227"
  license "Proprietary"

  on_macos do
    on_intel do
      url "https://github.com/kodexa-ai/kdx-cli-releases/releases/download/v2026.11.0-develop-32016774227/kdx-dev_2026.11.0-develop-32016774227_darwin_x86_64.tar.gz"
      sha256 "bb437f93d1ea3a64a625d0c4be32c6628d2e2610aa07cf1c2b2a88edfcce3675"

      def install
        bin.install "kdx-dev"
      end
    end
    on_arm do
      url "https://github.com/kodexa-ai/kdx-cli-releases/releases/download/v2026.11.0-develop-32016774227/kdx-dev_2026.11.0-develop-32016774227_darwin_arm64.tar.gz"
      sha256 "2c2d041a296137a27466bcd74c3e2693c7373ac4632f40880e256cae8896f3f2"

      def install
        bin.install "kdx-dev"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kodexa-ai/kdx-cli-releases/releases/download/v2026.11.0-develop-32016774227/kdx-dev_2026.11.0-develop-32016774227_linux_x86_64.tar.gz"
        sha256 "70e7c757c50550f048265ff4960f1a1cb1bdb8ebf1c95ff16fd23af043df4e68"

        def install
          bin.install "kdx-dev"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kodexa-ai/kdx-cli-releases/releases/download/v2026.11.0-develop-32016774227/kdx-dev_2026.11.0-develop-32016774227_linux_arm64.tar.gz"
        sha256 "be36f4cd5767cf2eb07e5b1753ead990ccea693837c66fdb26e8b25a595c5f86"

        def install
          bin.install "kdx-dev"
        end
      end
    end
  end

  def caveats
    <<~EOS
      This is a development pre-release of the Kodexa CLI.
      The binary is installed as 'kdx-dev' so it can coexist with the stable 'kdx'.

      To get started:
        kdx-dev --help

      For the stable version:
        brew install kodexa-ai/tap/kdx

      For support: support@kodexa.com
    EOS
  end

  test do
    system "#{bin}/kdx-dev", "--version"
  end
end
