# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kdx < Formula
  desc "Kodexa CLI - Command-line interface for Kodexa platform"
  homepage "https://www.kodexa.com"
  version "2026.2.0-22490308938"
  license "Proprietary"

  on_macos do
    on_intel do
      url "https://github.com/kodexa-ai/kdx-cli-releases/releases/download/v2026.2.0-22490308938/kdx_2026.2.0-22490308938_darwin_x86_64.tar.gz"
      sha256 "27d874399f674fad2a57ecc315f628acd842340e892f0ad6e3bee1d062c3559a"

      def install
        bin.install "kdx"
      end
    end
    on_arm do
      url "https://github.com/kodexa-ai/kdx-cli-releases/releases/download/v2026.2.0-22490308938/kdx_2026.2.0-22490308938_darwin_arm64.tar.gz"
      sha256 "58a760f32db388cbf46e698aa23cae52301265880bb286f08c9f7eda5986d136"

      def install
        bin.install "kdx"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kodexa-ai/kdx-cli-releases/releases/download/v2026.2.0-22490308938/kdx_2026.2.0-22490308938_linux_x86_64.tar.gz"
        sha256 "aea94c6bfeab71e41d89c16d34e4511c235c9977e98014d22abecad8c6e38ef6"

        def install
          bin.install "kdx"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kodexa-ai/kdx-cli-releases/releases/download/v2026.2.0-22490308938/kdx_2026.2.0-22490308938_linux_arm64.tar.gz"
        sha256 "1c4e32167257d10f70cdb4f1cf2d0ab04e890eb69e791301c4b93bac457f1ec6"

        def install
          bin.install "kdx"
        end
      end
    end
  end

  def caveats
    <<~EOS
      This is proprietary software from Kodexa, Inc.

      To get started:
        kdx --help

      For support: support@kodexa.com
    EOS
  end

  test do
    system "#{bin}/kdx", "--version"
  end
end
