# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kdx < Formula
  desc "Kodexa CLI - Command-line interface for Kodexa platform"
  homepage "https://www.kodexa.com"
  version "2026.12.0-36530281026"
  license "Proprietary"

  on_macos do
    on_intel do
      url "https://github.com/kodexa-ai/kdx-cli-releases/releases/download/v2026.12.0-36530281026/kdx_2026.12.0-36530281026_darwin_x86_64.tar.gz"
      sha256 "2c9076d6f8b81c21e17db0dbe5abd5ef8d729eecef757696ddb11673e4bc4677"

      def install
        bin.install "kdx"
      end
    end
    on_arm do
      url "https://github.com/kodexa-ai/kdx-cli-releases/releases/download/v2026.12.0-36530281026/kdx_2026.12.0-36530281026_darwin_arm64.tar.gz"
      sha256 "a2337aab7069fcc235da39038a6a60a749fbd6391dc122811e6bf9705bdf02fd"

      def install
        bin.install "kdx"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kodexa-ai/kdx-cli-releases/releases/download/v2026.12.0-36530281026/kdx_2026.12.0-36530281026_linux_x86_64.tar.gz"
        sha256 "49a2b8cf2c8758a259bf046dd044696318eb4f9ca2e413baa48e7688b1d72143"

        def install
          bin.install "kdx"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kodexa-ai/kdx-cli-releases/releases/download/v2026.12.0-36530281026/kdx_2026.12.0-36530281026_linux_arm64.tar.gz"
        sha256 "e6978e33bbc97cb878facb28f56a8002126819f77da1318cb925dbe2c2bc1271"

        def install
          bin.install "kdx"
        end
      end
    end
  end

  def caveats
    <<~EOS
      This is proprietary software from Kodexa, Inc.

      To get started:
        kdx --help

      For support: support@kodexa.com
    EOS
  end

  test do
    system "#{bin}/kdx", "--version"
  end
end
