# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kdx < Formula
  desc "Kodexa CLI - Command-line interface for Kodexa platform"
  homepage "https://www.kodexa.com"
  version "2026.11.0-32892894908"
  license "Proprietary"

  on_macos do
    on_intel do
      url "https://github.com/kodexa-ai/kdx-cli-releases/releases/download/v2026.11.0-32892894908/kdx_2026.11.0-32892894908_darwin_x86_64.tar.gz"
      sha256 "73b9c8cf9433836b58dfe385e60769a13b79ded90a78c1b98c64d26c8b725aef"

      def install
        bin.install "kdx"
      end
    end
    on_arm do
      url "https://github.com/kodexa-ai/kdx-cli-releases/releases/download/v2026.11.0-32892894908/kdx_2026.11.0-32892894908_darwin_arm64.tar.gz"
      sha256 "b9eaaad8a4de841a002c7d625c2b970c62cf377ef7f1d35210369f5280a88453"

      def install
        bin.install "kdx"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kodexa-ai/kdx-cli-releases/releases/download/v2026.11.0-32892894908/kdx_2026.11.0-32892894908_linux_x86_64.tar.gz"
        sha256 "c1d82f9e03a56832fd4519267475d979885cdbf48fa354f55ca483fce1458dd7"

        def install
          bin.install "kdx"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kodexa-ai/kdx-cli-releases/releases/download/v2026.11.0-32892894908/kdx_2026.11.0-32892894908_linux_arm64.tar.gz"
        sha256 "2485755c2c88f09703223f5ddb8198eaeb132b729b33fff9eb08c87a76235961"

        def install
          bin.install "kdx"
        end
      end
    end
  end

  def caveats
    <<~EOS
      This is proprietary software from Kodexa, Inc.

      To get started:
        kdx --help

      For support: support@kodexa.com
    EOS
  end

  test do
    system "#{bin}/kdx", "--version"
  end
end
