# Copyright (c) 2026 Kodexa, Inc. All rights reserved.
# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kdx < Formula
  desc "Kodexa CLI - Command-line interface for Kodexa platform"
  homepage "https://www.kodexa.com"
  version "0.1.2"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/kodexa-ai/kdx-cli/releases/download/v0.1.2/kdx_0.1.2_darwin_arm64.tar.gz"
      sha256 `curl -sL https://github.com/kodexa-ai/kdx-cli/releases/download/v0.1.2/checksums.txt | grep darwin_arm64 | cut -d' ' -f1`.strip
    end
    if Hardware::CPU.intel?
      url "https://github.com/kodexa-ai/kdx-cli/releases/download/v0.1.2/kdx_0.1.2_darwin_x86_64.tar.gz"
      sha256 `curl -sL https://github.com/kodexa-ai/kdx-cli/releases/download/v0.1.2/checksums.txt | grep darwin_x86_64 | cut -d' ' -f1`.strip
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/kodexa-ai/kdx-cli/releases/download/v0.1.2/kdx_0.1.2_linux_x86_64.tar.gz"
      sha256 `curl -sL https://github.com/kodexa-ai/kdx-cli/releases/download/v0.1.2/checksums.txt | grep linux_x86_64 | cut -d' ' -f1`.strip
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kodexa-ai/kdx-cli/releases/download/v0.1.2/kdx_0.1.2_linux_arm64.tar.gz"
      sha256 `curl -sL https://github.com/kodexa-ai/kdx-cli/releases/download/v0.1.2/checksums.txt | grep linux_arm64 | cut -d' ' -f1`.strip
    end
  end

  def install
    bin.install "kdx"
  end

  def caveats
    <<~EOS
      This is proprietary software from Kodexa, Inc.

      To get started:
        kdx --help

      For support: support@kodexa.com
    EOS
  end

  test do
    system "#{bin}/kdx", "--version"
  end
end
